package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import control.login.*;

/**
 *
 * @author alialdobyan
 */
public class LoginMenu extends javax.swing.JFrame {

	/**
	 * Creates new form LoginMenu
	 */
	public LoginMenu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel_Username = new javax.swing.JLabel();
		jTextField_username = new javax.swing.JTextField();
		jLabel_password = new javax.swing.JLabel();
		jPasswordField_password = new javax.swing.JPasswordField();
		jButton_Cancel = new javax.swing.JButton();
		jButton_Login = new javax.swing.JButton();
		jButton_Register = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(new java.awt.Point(600, 300));

		jLabel_Username.setText("Username");

		jLabel_password.setText("Password");

		jButton_Cancel.setText("Cancel");
		jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_CancelActionPerformed(evt);
			}
		});

		jButton_Login.setText("Login");
		jButton_Login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_LoginActionPerformed(evt);
				} catch (Exception ex) {
					Logger.getLogger(LoginMenu.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});

		jButton_Register.setText("Register");
		jButton_Register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_RegisterActionPerformed(evt);
			}
		});
		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(16, 16, 16)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(82, 82, 82)
						.addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
						.addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(21, 21, 21))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel_Username).addComponent(jLabel_password))
								.addGap(48, 48, 48)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 299,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE,
												299, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 0, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(88, 88, 88)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_Username))
						.addGap(46, 46, 46)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_password))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton_Cancel).addComponent(jButton_Login)
								.addComponent(jButton_Register))
						.addGap(29, 29, 29)));

		pack();
	}// </editor-fold>

	private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:

		String username = jTextField_username.getText();
		String password = String.valueOf(jPasswordField_password.getPassword());

		Login login = new Login();
		boolean dispose = login.login(username, password);
		if (dispose) 
			{ this.dispose(); }
		
	}

	private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		RegisterMenu register = new RegisterMenu();
		register.setVisible(true);
		this.dispose();
	}
	
	private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton jButton_Cancel;
	private javax.swing.JButton jButton_Login;
	private javax.swing.JButton jButton_Register;
	private javax.swing.JLabel jLabel_Username;
	private javax.swing.JLabel jLabel_password;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPasswordField jPasswordField_password;
	private javax.swing.JTextField jTextField_username;
	// End of variables declaration
}
